name: Release Service

on:
  push:

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - id: matrix
        run: |
          echo '::set-output name=value::[\"a\", \"b\", \"c\"]'
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"

#    - name: envs
#      run: |
#        echo ${{ steps.branches.outputs.value }}
#        echo ${{ github.event.repository.name }}
#        echo ${{ steps.string.outputs.lowercase }}
#        echo ${GITHUB_REF#refs/tags/}
#        echo ${REPO}
#        echo "indexprices-${{ matrix.version }}"
