name: Build UAT Python

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      repository_type:
        required: true
        type: string
      release_version:
        required: true
        type: string
      python_version:
        description: "Python version for Docker build (e.g. 3.9, 3.10, 3.11)"
        required: false
        type: string
        default: "3.9"
    secrets:
      ST_DOCKER_USER:
        required: true
      ST_DOCKER_PASSWORD:
        required: true
      AZURE_CONTAINER_REGISTRY:
        required: true
      UAT_GIT_TOKEN:
        required: true

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"

    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name }}

    - name: Build & Push Docker image (ACR)
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ST_DOCKER_USER }}
        password: ${{ secrets.ST_DOCKER_PASSWORD }}
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        repository: spot/myjetwallet.${{ steps.string.outputs.lowercase }}
        path: .
        tags: ${{ inputs.release_version }}
        tag_with_ref: false
        push: true
        build_args: |
          PYTHON_VERSION=${{ inputs.python_version }},app_version=myjetwallet.${{ steps.string.outputs.lowercase }}:${{ inputs.release_version }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

  k8s-deploy:
    needs: [build]
    runs-on: self-hosted

    steps:
    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name }}

    - name: get uat k8s yamls
      uses: actions/checkout@v2
      with:
        repository: MyJetWallet/kubernates-infrastructure
        ref: uat
        token: ${{ secrets.UAT_GIT_TOKEN }}

    - run: |
        pattern=myjetwallet.${{ steps.string.outputs.lowercase }}:.*$
        imagename=myjetwallet.${{ steps.string.outputs.lowercase }}:${{ inputs.release_version }}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git status | grep -q modified; then git commit -a -m "Update version of service myjetwallet.${{ steps.string.outputs.lowercase }}" && git push; fi

  docker-deploy:
    needs: [build, k8s-deploy]
    runs-on: self-hosted

    steps:
    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name }}

    - name: get uat docker yamls
      uses: actions/checkout@v2
      with:
        repository: MyJetWallet/docker-infrastructure
        ref: uat
        token: ${{ secrets.UAT_GIT_TOKEN }}

    - run: |
        pattern=myjetwallet.${{ steps.string.outputs.lowercase }}:.*$
        imagename=myjetwallet.${{ steps.string.outputs.lowercase }}:${{ inputs.release_version }}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git status | grep -q modified; then git commit -a -m "Update version of service myjetwallet.${{ steps.string.outputs.lowercase }}" && git push; fi
