name: BUILD UAT

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      repository_name_second:
        required: true
        type: string
      repository_output_second:
        required: true
        type: string           
      repository_type:
        required: true
        type: string
      release_version:
        required: true
        type: string
    secrets:
      ST_DOCKER_USER:
        required: true
      ST_DOCKER_PASSWORD:
        required: true
      AZURE_CONTAINER_REGISTRY:
        required: true
      UAT_GIT_TOKEN:
        required: true
      NUGET_AUTH_TOKEN:
        required: true

jobs:
  build:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "/home/monfex"

    steps:
    - uses: actions/checkout@v3

    - name: Set .NET root
      run: echo "DOTNET_ROOT=/home/monfex" >> $GITHUB_ENV
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        source-url: https://nuget.pkg.github.com/myjetwallet/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"
        
    - name: list nugets
      run: dotnet nuget list source
      
    - name: Restore
      run: dotnet restore
      continue-on-error: true
      
    - name: Build microservice
      run: dotnet build --no-restore --configuration Release /p:AssemblyVersion=${{ inputs.release_version }}

    - name: Test microservice
      run: dotnet test --no-build --configuration Release

    - name: Publish Service
      run: dotnet publish ./src/*${{ inputs.repository_name }}/*${{ inputs.repository_name }}.csproj --configuration Release /p:AssemblyVersion=${{ inputs.release_version }} --output ./publish-api

    - name: Publish Service ${{ inputs.repository_name_second }}
      run: dotnet publish ./src/*${{ inputs.repository_name_second }}/*${{ inputs.repository_name_second }}.csproj --configuration Release /p:AssemblyVersion=${{ inputs.release_version }} --output ${{ inputs.repository_output_second }}

    - name: Check Service dir
      run: ls ./publish-api

    - name: Check Service dir ${{ inputs.repository_name_second }}
      run: ls ${{ inputs.repository_output_second }}

    - name: copy Dockerfile
      run: cp ./publish-api/Dockerfile ./${{ inputs.repository_output_second }}/Dockerfile

    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name }}

    - id: string_second
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name_second }}

    - name: Publish image azure
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ST_DOCKER_USER }}
        password: ${{ secrets.ST_DOCKER_PASSWORD }}
        path: ./publish-api
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        repository: spot/myjetwallet.${{ steps.string.outputs.lowercase }}
        tag_with_ref: true
        build_args: app_version=myjetwallet.${{ steps.string.outputs.lowercase }}:{{ inputs.release_version }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

    - name: Publish image azure ${{ inputs.repository_name_second }}
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ST_DOCKER_USER }}
        password: ${{ secrets.ST_DOCKER_PASSWORD }}
        path: ${{ inputs.repository_output_second }}
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        repository: spot/myjetwallet.${{ steps.string_second.outputs.lowercase }}
        tag_with_ref: true
        build_args: app_version=myjetwallet.${{ steps.string_second.outputs.lowercase }}:{{ inputs.release_version }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

  k8s-deploy:
    needs: [build]
    runs-on: self-hosted

    steps:
    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name }}

    - id: string_second
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name_second }}

    - name: get uat k8s yamls
      uses: actions/checkout@v2
      with:
        repository: MyJetWallet/kubernates-infrastructure
        ref: uat
        token: ${{ secrets.UAT_GIT_TOKEN }}
    - run: |
        pattern=myjetwallet.${{ steps.string.outputs.lowercase }}:.*$
        imagename=myjetwallet.${{ steps.string.outputs.lowercase }}:${{ inputs.release_version }}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git status | grep -q modified; then git commit -a -m "Update version of service myjetwallet.${{ steps.string.outputs.lowercase }}" && git push; fi
        pattern=myjetwallet.${{ steps.string_second.outputs.lowercase }}:.*$
        imagename=myjetwallet.${{ steps.string_second.outputs.lowercase }}:${{ inputs.release_version }}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git status | grep -q modified; then git commit -a -m "Update version of service myjetwallet.${{ steps.string_second.outputs.lowercase }}" && git push; fi

  docker-deploy:
    needs: [build, k8s-deploy]
    runs-on: self-hosted
    
    steps:
    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name }}

    - id: string_second
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name_second }}

    - name: get uat docker yamls
      uses: actions/checkout@v2
      with:
        repository: MyJetWallet/docker-infrastructure
        ref: uat
        token: ${{ secrets.UAT_GIT_TOKEN }}
    - run: |
        pattern=myjetwallet.${{ steps.string.outputs.lowercase }}:.*$
        imagename=myjetwallet.${{ steps.string.outputs.lowercase }}:${{ inputs.release_version }}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git status | grep -q modified; then git commit -a -m "Update version of service myjetwallet.${{ steps.string.outputs.lowercase }}" && git push; fi
        pattern=myjetwallet.${{ steps.string_second.outputs.lowercase }}:.*$
        imagename=myjetwallet.${{ steps.string_second.outputs.lowercase }}:${{ inputs.release_version }}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git status | grep -q modified; then git commit -a -m "Update version of service myjetwallet.${{ steps.string_second.outputs.lowercase }}" && git push; fi
    
