name: BUILD UAT

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      repository_type:
        required: true
        type: string
      release_version:
        required: true
        type: string
    secrets:
      ST_DOCKER_USER:
        required: true
      ST_DOCKER_PASSWORD:
        required: true
      AZURE_CONTAINER_REGISTRY:
        required: true
      UAT_GIT_TOKEN:
        required: true
        
jobs:
  build:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "/home/monfex"

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.*
#         source-url: https://nuget.pkg.github.com/myjetwallet/index.json
#       env:
#         NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"

    - name: remove nugets myjetwallet
      run: dotnet nuget remove source myjetwallet
      continue-on-error: true
    - name: remove nugets nuget.org
      run: dotnet nuget remove source nuget.org
      continue-on-error: true
    - name: add nugets
      run: dotnet nuget add  source  --name myjetwallet https://nuget.pkg.github.com/myjetwallet/index.json
      continue-on-error: true
    - name: list nugets
      run: dotnet nuget list source
    - name: Restore
      run: dotnet restore
      continue-on-error: true

    - name: Build microservice
      run: dotnet build --no-restore --configuration Release /p:AssemblyVersion=${{ inputs.release_version }}

    - name: Test microservice
      run: dotnet test --no-build --configuration Release

    - name: Publish Service
      run: dotnet publish ./src/${{ inputs.repository_name }}/${{ inputs.repository_name }}.csproj --configuration Release /p:AssemblyVersion=${{ inputs.release_version }} --output ./publish-api

    - name: Check Service dir
      run: ls ./publish-api

    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name }}

    - name: Publish image azure
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ST_DOCKER_USER }}
        password: ${{ secrets.ST_DOCKER_PASSWORD }}
        path: ./publish-api
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        repository: spot/myjetwallet.${{ steps.string.outputs.lowercase }}
        tag_with_ref: true
        build_args: app_version=myjetwallet.${{ steps.string.outputs.lowercase }}:{{ inputs.release_version }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

  docker-deploy:
    needs: [build]
    runs-on: self-hosted
    
    steps:
    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ inputs.repository_name }}

    - name: get uat docker yamls
      uses: actions/checkout@v2
      with:
        repository: MyJetWallet/finance-infrastructure
        ref: master
        token: ${{ secrets.UAT_GIT_TOKEN }}
    - run: |
        pattern=myjetwallet.${{ steps.string.outputs.lowercase }}:.*$
        imagename=myjetwallet.${{ steps.string.outputs.lowercase }}:${{ inputs.release_version }}
        reg=$"s/${pattern}/${imagename}/g"
        echo $reg
        find . -type f -name "*.*ml" -exec sed -i -r $reg {} \;
        git config user.name github-actions
        git config user.email github-actions@github.com
        if git status | grep -q modified; then git commit -a -m "Update version of service ${{ steps.string.outputs.lowercase }}" && git push; fi
