name: Release Service

on:
  push:

jobs:
  call-workflow-passing-data:
    uses: MyJetWallet/DevOps/blob/master/.github/workflows/reuse.yml@master
    with:
      username: pashka1990
    secrets:
      envPAT: ${{ secrets.PAT_TOKEN }}
