name: Release Service

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: envs
      run: |
        echo ${GITHUB_REF#refs/tags/}
        echo ${{ github.event.repository.private }}
