name: Release Service

on:
  push:
    tags: "2.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      uses: vazco/github-actions-branch-name@v1
      id: branch


    - name: downcase REPO
      run: echo REPO=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
    - id: string
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.event.repository.name }}

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"

    - name: Name of branch uat
      id: branches
      uses: ashley-taylor/regex-property-action@1.2
      with:
        value: ${{ github.ref }}
        regex: ".*/"
        flags: ""
        replacement: ""

    - name: envs
      run: |
        echo ${{ steps.branches.outputs.value }}
        echo ${{ github.event.repository.name }}
        echo ${{ steps.string.outputs.lowercase }}
        echo ${GITHUB_REF#refs/tags/}
        echo ${REPO}
        env
