name: Release Service

on:
  workflow_call:
    inputs:
      test:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.runner_id.outputs.runner }}
    steps:
      - name: Check repo
        id: runner_id
        run: |
          if [ ${{ github.event.repository.private }} == true ]; then
            echo "::set-output name=runner::self-hosted"
          else
            echo "::set-output name=runner::ubuntu-latest"
          fi

  job1:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - run: echo "My runner is ${{ needs.setup.outputs.runner }}"
      - run: echo ${{ github.event.inputs.test }}
