name: BUILD TEST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Protobuf compiler
      run: sudo apt install protobuf-compiler -yq
    - name: Build
      run: /home/monfex/.cargo/bin/cargo build --verbose
    - name: Run tests
      run: /home/monfex/.cargo/bin/cargo test --verbose
