name: BUILD TEST

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Protobuf compiler
      run: sudo apt install protobuf-compiler -yq
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
