name: test flow

on:
  push:
    branches:    
      - master
    tags:        
      - 2.*

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.runner_id.outputs.runner }}
    steps:
      - name: Check repo
        id: runner_id
        run: |
          if [ ${{ github.event.repository.private }} == true ]; then
            echo "::set-output name=runner::self-hosted"
          else
            echo "::set-output name=runner::ubuntu-latest"
          fi

  job1:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - run: echo "My runner is ${{ needs.setup.outputs.runner }}"

  job2:
    needs: [setup]
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - name: Build with Maven
        if: github.ref == 'refs/heads/master'
        run: echo 'push'
      - name: Deploy with Maven
        - if: github.event_name == 'release' && github.event.action == 'created'
        run: echo "Deploying tag ${{ github.ref }}"
